export const DATE_CREATE_REQUEST = "DATE_CREATE_REQUEST";
export const DATE_CREATE_SUCCESS = "DATE_CREATE_SUCCESS";
export const DATE_CREATE_FAIL = "DATE_CREATE_FAIL";
export const DATE_CREATE_RESET = "DATE_CREATE_RESET";

export const DATE_LIST_REQUEST = "DATE_LIST_REQUEST";
export const DATE_LIST_SUCCESS = "DATE_LIST_SUCCESS";
export const DATE_LIST_FAIL = "DATE_LIST_FAIL";